spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
#    host: smtp.office365.com       //For Outlook
    port: 587
#    port: 25          //If encryption is not needed
    username: vijaymohanofficial@gmail.com
#    Not personal mail password, its app password
    password: etrs ujcp oeyu axsd
    properties:
      mail:
        smtp:
          auth: true
#          Using Encryption
          starttls:
            enable: true

server:
  port: 8090
#  servlet:
#    context-path: journalApp

weather:
  api:
    key: f568f59803cf6633be3897daabbfd281
#Adding custom path for Swagger UI
springdoc:
  swagger-ui:
    path: /docs